
% bestTheta is a single vector for theta that will generate a matrix with
% as many repetitons as desired in the same structure as the ParFull LHS_ThetaSampling
% generated by 

% samps is an integer indicating how many sampels for the parameters one
% wants

function [ParFull] = RepeatedInitialGuess(bestTheta, samps)

    ParFull = zeros(samps, length(bestTheta));
    for i = 1:samps
        ParFull(i,:) = bestTheta;
    end


end