
function [Results]=nomad_kernel(problem,opts,varargin)
% function [Results]=ess_kernel(problem,opts,varargin)
% Function   : eSS Release 2014B - AMIGO2014bench VERSION WITH eSS MAY-2014-BUGS FIXED - JRB
% Written by : Process Engineering Group IIM-CSIC (jegea@iim.csic.es)
% Created on : 12/03/2008
% Last Update: 20/06/2013
% Email      : gingproc@iim.csic.es
%
% (c) CSIC, Spanish Council for Scientific Research
%
% Global optimization algorithm for MINLP's based on Scatter Search
%
%   eSS attempts to solve problems of the form:
%       min F(x)  subject to:  ceq(x) = 0 (equality constraints)
%        x                     c_L <= c(x) <= c_U (inequality constraints)
%                              x_L <= x <= x_U (bounds on the decision
%                              variables)
%
% Constraint functions, if applicable, must be declared in the same script as the
% objective function as a second output argument:
% e.g., [f,c]=myfunction(x)
%       f=objective function value
%       g=vector containing the constraints
%       return
%
% Please have a look at the manual before using eSS
%
%       USAGE: Results=ess_kernel(problem,opts,p1,p2,....,pn);
%
% INPUT PARAMETERS:
% ****************
%   problem - Structure containing problem settings
%       problem.f   = Name of the file containing the objective
%                     function (String)
%       problem.x_L = Lower bounds of decision variables (vector)
%       problem.x_U = Upper bounds of decision variables (vector)
%       problem.x_0 = Initial point(s) (optional; vector or matrix)
%       problem.f_0 = Function values of initial point(s) (optional) These
%       value MUST correspond to feasible points.
%
%       NOTE:The dimension of f_0 and x_0 may be different. For example, if
%       we want to introduce 5 initial points but we only know the values
%       for 3 of them, x_0 would have 5 rows whereas f_0 would have only 3
%       elements. It is mandatory that the first 3 rows of x_0 correspond
%       to the values of f_0
%
%       Additionally, fill the following fields if your problem has
%       non-linear constraints
%       problem.neq     = Number of equality constraints (Integer; do not define it
%                         if there are no equality constraints)
%       problem.c_L     = Lower bounds of nonlinear inequality constraints
%                        (vector)
%       problem.c_U     = Upper bounds of nonlinear inequality constraints
%                         (vector)
%       problem.int_var = Number of integer variables (Integer)
%       problem.bin_var = Number of binary variables  (Integer)
%       problem.vtr     = Objective function value to be reached (optional)
%
%
% NOTE: The order of decision variables is x=[cont int bin]
%
%   opts - Structure containing options (if set as opts=[] defaults options
%          will be loaded) Type "ssm_kernel" or "ssm_kernel('defaults')" to
%          get the default options
%
%       User options
%           opts.maxfeval    = Maximum number of function evaluations
%                             (Default 1000)
%           opts.maxtime    = Maximum CPU time in seconds (Default 60)
%           opts.iterprint  = Print each iteration on screen: 0-Deactivated
%                             1-Activated (Default 1)
%           opts.plot       = Plots convergence curves: 0-Deactivated,
%                             1-Plot curves on line, 2-Plot final results
%                             (Default 0)
%           opts.weight     = Weight that multiplies the penalty term added
%                             to the objective function in constrained
%                             problems (Default 1e6)
%           opts.log_var    = Indexes of the variables which will be used
%                             to generate diverse solutions in different
%                             orders of magnitude (vector)
%           opts.tolc       = Maximum absolute violation of the constraints
%                             (Default 1e-5)
%           opts.prob_bound = Probability (0-1) of biasing the search towards
%                             the bounds (Default 0.5)
%           opts.inter_save = Saves results in a mat file in intermediate
%                             iterations. Useful for very long runs
%                             (Binary; Default = 0)
%           opts.n_stuck    = Number of consecutive iterations without
%                             significant improvement before the search
%                             stops. Default = 0 (not applicable);
%
%       Global options
%           opts.dim_refset         = Number of elements in Refset
%                                     (Integer; automatically calculated)
%           opts.ndiverse           = Number of solutions generated by the
%                                     diversificator (Default 10*nvar)
%           opts.combination        = Type of combination of Refset
%                                     elements (Default 1)
%                                     1: hyper-rectangles
%                                     2: linear combinations
%
%       Local options
%           opts.local.solver               = Choose local solver
%                                             0: Local search deactivated
%                                             'fmincon'(Default),
%                                             'fminsearch', 'solnp'
%                                             'n2fb','dn2fb','dhc','hooke'
%                                             'ipopt','misqp','lsqnonlin'
%           opts.local.tol                  = Level of tolerance in local
%                                             search. 1: Relaxed; 2: Medium
%                                             3: Tight (default: 2 in
%                                             intermediate searches and 3
%                                             in the final stage).
%           opts.local.iterprint            = Print each iteration of local
%                                             solver on screen (Binary;
%                                             default = 0)
%           opts.local.n1                   = Number of iterations
%                                             before applying
%                                             local search for the 1st time
%                                             (Default 1)
%           opts.local.n2                   = Minimum number of iterations
%                                             in the global
%                                             phase between 2 local calls
%                                             (Default 10)
%           opts.local.balance              = Balances between quality (=0)
%                                             and diversity (=1) for
%                                             choosing initial points for
%                                             the local search (default
%                                             0.5)
%           opts.local.finish               = Applies local search to the
%                                             best solution found once the
%                                             optimization if finished
%                                             (same values as
%                                             opts.local.solver)
%           opts.local.bestx                = When activated (i.e. =1) only
%                                             applies local search to the
%                                             best solution found to
%                                             date,ignoring filters
%                                             (Default=0)
%
%
%   p1,p2... :  optional input parameters to be passed to the objective
%   function
%
%
% OUTPUT PARAMETERS:
% *****************
% A file called "ssm_report.mat" is generated containing.
%
%   problem - Structure containing problem settings
%   opts    - Structure containing all options
%   Results - Structure containing results
%
% Fields in Results
%       Results.fbest                   = Best objective function value
%                                         found after the optimization
%       Results.xbest                   = Vector providing the best
%                                         function value
%       Results.cpu_time                = Time in seconds consumed in the
%                                         optimization
%       Results.f                       = Vector containing the best
%                                         objective function value after each
%                                         iteration
%       Results.x                       = Matrix containing the best vector
%                                         after each iteration
%       Results.time                    = Vector containing the cpu time
%                                         consumed after each iteration
%       Results.neval                   = Vector containing the number of
%                                         function evaluations after each
%                                         iteration
%       Results.numeval                 = Number of function evaluations
%       Results.local_solutions         = Local solutions found by the
%                                         local solver (in rows)
%       Results.local_solutions_values  = Function values of the local
%                                         solutions
%       Results.end_crit                = Criterion to finish the
%                                         optimization
%                                         1: Maximal number of function
%                                         evaluations achieved
%                                         2: Maximum allowed CPU Time
%                                         achieved
%                                         3: Value to reach achieved
%
%              NOTE: To plot convergence curves type:
%              stairs(Results.time,Results.f) or stairs(Results.neval,Results.f)
% REFERENCES
%
% If you use eSS and publish the results, please cite the following papers:
%
% Egea, J.A., Balsa-Canto, E., García, M.S.G., Banga, J.R. (2009) Dynamic
% optimization of nonlinear processes with an enhanced scatter search
% method. Industrial & Engineering Chemistry Research 49(9): 4388-4401.
%
% Egea, J.A., Martí, R., Banga, J.R. (2010) An evolutionary method for
% complex-process optimization. Computers & Operations Research 37(2):
% 315-324.


global input_par
global stopOptimization
stopOptimization=0;

%Initialize time
cpu_time=cputime;


% if isfield(opts,'iterprint') & opts.iterprint
%     vers='eSS R2014B  IIM-CSIC, Vigo, Spain';% AMIGO2014bench VERSION - JRB
%     fprintf('%-9s %s\n','Version:',  vers);
% end

fprintf('\n');
fprintf('------------------------------------------------------------------------------ \n');
fprintf(' Nomad - Nonlinear Optimization by Mesh Adaptive Direct Search    \n');
% fprintf('<c> IIM-CSIC, Vigo, Spain -  email: gingproc@iim.csic.es \n');
fprintf('------------------------------------------------------------------------------ \n\n');


%Initialize the number of function evaluations and a stop variable
nfuneval=0;
fin=0;
nreset=0;
% local_solver=opts.local.solver;

if not(isfield(opts,'maxfeval')) && not(isfield(opts,'maxtime'))
    fprintf('WARNING:Either opts.maxfeval or opts.maxtime must be defined as a stop criterion \n')
    fprintf('Define any of these options and rerun \n')
    Results=[];
    return
else
    if not(isfield(opts,'maxfeval'))
        maxfeval=1e12;
    else
        maxfeval=opts.maxfeval;
    end
    if not(isfield(opts,'maxtime'))
        maxtime=1e12;
    else
        maxtime=opts.maxtime;
    end
end

%Load default values for the options
default=ssm_defaults_MINLP;

%Display default options
if (nargin < 1) | (isstr(problem) & isequal(problem, 'defaults')) % pass default options
    disp('Default options returned (type "help ssm_kernel" for help).');
    fprintf('\n');
    disp('Global options')
    disp(default)
    Results = 'End of default options display';
    return
end

if nargin<2, opts=[]; end

% check regularization for iterative display of the reg. cost and penalty
reg_flag = 0;
if nargin == 5
    if isfield(varargin{1},'minlpsol') && isfield(varargin{1}.minlpsol,'regularization') && varargin{1}.nlpsol.regularization.ison
        reg_flag = 1;
        amigo_inputs = varargin{1};
        amigo_privstruct = varargin{2};
    end
end 

%Set all options
opts=ssm_optset_MINLP(default,opts);

input_par=varargin;

x_U=problem.x_U;
x_L=problem.x_L;

%Check if bounds have the same dimension
if length(x_U)~=length(x_L)
    disp('Upper and lower bounds have different dimension!!!!')
    disp('EXITING')
    Results=[];
    return
else
    %Number of decision variables
    nvar=length(x_L);
end

if not(isfield(problem,'x_0')), x_0=[]; else, x_0=problem.x_0; end

if not(isfield(problem,'f_0'))
    f_0=[];
    fbest=inf;
else
    f_0=problem.f_0;
    %Transform in column vector
    if size(f_0,1)==1
        f_0=f_0';
    end
    [fbest,iii]=min(f_0);
    xbest=x_0(iii,:);
end
if not(isfield(problem,'neq')) | isempty(problem.neq), neq=0; else, neq=problem.neq; end
if not(isfield(problem,'c_U')), c_U=[]; c_L=[]; else, c_U=problem.c_U; c_L=problem.c_L; end
if not(isfield(problem,'int_var')) | isempty(problem.int_var), int_var=0; else, int_var=problem.int_var; end
if not(isfield(problem,'bin_var')) | isempty(problem.bin_var), bin_var=0; else, bin_var=problem.bin_var; end
if not(isfield(problem,'vtr')), vtr=[]; else, vtr=problem.vtr; end


%Change to rows if necessary
if size(x_L,2)==1, x_L=x_L'; end
if size(x_U,2)==1, x_U=x_U'; end
if size(c_L,2)==1, c_L=c_L'; end
if size(c_U,2)==1, c_U=c_U'; end

%User options
iterprint=opts.iterprint;
prob_bound=opts.prob_bound;
inter_save=opts.inter_save;

plot_results=opts.plot;
weight=opts.weight;
tolc=opts.tolc;
log_var=opts.log_var;


%Global options
dim_refset=opts.dim_refset;
if ischar(dim_refset) || isempty(dim_refset)
    nnn=roots([1  -1 -10*nvar/1]);
    iii=find(nnn>0);
    dim_refset=ceil(nnn(iii));
    if mod(dim_refset,2), dim_refset=dim_refset+1; end
    if iterprint
        fprintf('%-9s %i\n','Refset size automatically calculated:',  dim_refset);
    end
end

ndiverse=opts.ndiverse;

if ischar(ndiverse)
    
    ndiverse=10*nvar;
    if iterprint
        fprintf('%-9s %i\n','Number of diverse solutions automatically calculated:',  ndiverse);
    end
    
elseif(isempty(ndiverse))
    
    ndiverse=10*nvar;
    if iterprint
        fprintf('%-9s %i\n','Number of diverse solutions automatically calculated:',  ndiverse);
    end
end

if ndiverse<dim_refset
    ndiverse=dim_refset;
end

initiate=opts.initiate;
combin=opts.combination;
n_stuck=opts.n_stuck;


%If there are equality constraints
if neq
    %Set the new bounds for all the constraints
    c_L=[zeros(1,neq) c_L];
    c_U=[zeros(1,neq) c_U];
end

if size(x_0,2)~=nvar, x_0=x_0'; end

nconst=length(c_U);

%Transform the objective function into a handle
if isa(problem.f,'function_handle')
    fobj = problem.f;
    problem.f = func2str(problem.f);
else
    fobj=str2func(problem.f);
end

isFjacDefined = 0;
if isfield(problem,'fjac') && ~isempty(problem.fjac)
    isFjacDefined = 1;
    
	if ischar(problem.fjac)
		fjac = str2func(problem.fjac);
	elseif isa(problem.fjac,'function_handle')
		fjac = problem.fjac;
	else
		error('fjac is neither a string nor a function handle.')
	end
end

%Check if the objecttive function has 2 output arguments in constrained
%problems
% if nconst
%     n_out_f=nargout(problem.f);
%     if n_out_f<2
%         fprintf('For constrained problems the objective function must have at least 2 output arguments \n');
%         fprintf('EXITING \n');
%         Results=[];
%         return
%     end
%     if local_solver & strcmp(local_solver,'fminsearch') | strcmp(local_solver,'hooke') | strcmp(local_solver,'dhc')
%         fprintf('Warning! %s might not provide the optimal solution for constrained problems \n',local_solver);
%     end
% end
% 
% if (int_var+bin_var) & local_solver & not(strcmp(local_solver,'misqp'))
%     fprintf('For problems with integer and/or binary variables you must use MISQP as a local solver \n');
%     fprintf('EXITING \n');
%     Results=[];
%     return
% end
% 
% if local_solver & strcmp(local_solver,'n2fb') | strcmp(local_solver,'dn2fb')| strcmp(local_solver,'nl2sol')
%     n_out_f=nargout(problem.f);
% else
%     ndata=[];
% end
ndata=[];

%Pasamos a logaritmo
xl_log=x_L;
xu_log=x_U;

aaa=find(xl_log(log_var)==0);

xl_log(log_var(aaa))=eps;

xl_log(log_var)=log(xl_log(log_var));
xu_log(log_var)=log(xu_log(log_var));


%Build auxiliary files in case local search is activated
% if local_solver
%     if isFjacDefined
%         ssm_aux_local(problem.f,problem.fjac,x_L,x_U,c_L,c_U,neq,local_solver,nvar,varargin{:});
%     else
%         ssm_aux_local(problem.f,[],x_L,x_U,c_L,c_U,neq,local_solver,nvar,varargin{:});
%     end
% end
% ssm_aux_local(problem.f,x_L,x_U,c_L,c_U,neq,local_solver,nvar,varargin{:});
%Initialize variables
stage_1=1;
n_minimo=0;
% n_critico=local_n1;
denom=2;
suit_to_local=ones(1,dim_refset);

local_solutions=[];
local_solutions_values=[];
initial_points=[];

Results.f=[];
Results.x=[];
Results.time=[];
Results.neval=[];
xbest=[];

%Possible combinations among the dim_refset elements in Refset, taken in pairs
ncomb=nchoosek(1:dim_refset,2);
MaxSubSet=(dim_refset^2-dim_refset)/2;
MaxSubSet2=2*MaxSubSet;


%We generate 5 solutions
solutions=zeros(ndiverse+5,nvar);

for i=1:5
    solutions(i,:)=(rand(1,nvar)+i-1)/5;
end

solutions(6:ndiverse+5,:)=rand(ndiverse,nvar);
solutions=solutions.*repmat(xu_log-xl_log,ndiverse+5,1)+repmat(xl_log,ndiverse+5,1);

% BUG FIXED - JRB - JUNE 2014
%if (int_var) | (bin_var)
%    solutions=ssm_round_int(solutions,int_var+bin_var,x_L,x_U);
%end
for i=1:ndiverse+5
       solutions(i,log_var)=exp(solutions(i,log_var));
end


l_f_0=length(f_0);
l_x_0=size(x_0,1);


%Put x_0 without their corresponding f_0 values at the beginning of solutions
solutions=[x_0(l_f_0+1:end,:); solutions];

temp=l_x_0-l_f_0;

sol=zeros(ndiverse+5+temp,nvar);
sol_val=zeros(ndiverse+5+temp,1);
sol_val_pen=zeros(ndiverse+5+temp,1);
sol_pen=zeros(ndiverse+5+temp,1);
sol_nlc=zeros(ndiverse+5+temp,nconst);

counter=1;

[nopts] = SetNomadOptions(opts);


% Objective
fun = fobj;
% Bounds
lb = x_L';
ub = x_U';
% Integer Constraints

if length(opts.xtype) ~= length(lb)
    opts.xtype=repmat('I', 1, length(lb));
end

xtype = opts.xtype;
%Initial Guess
x0 = x_0'; 

nlcon=[];
nlrhs=[];
global totfeval
totfeval = [];
% Call to NomadSolver
[x, fval, exitflag, iter, nfval] = nomad(fun,x0,lb,ub,nlcon,nlrhs,xtype,nopts);

% csvDat1 = readtable(strrep(nopts.history_file, '.csv', '.0.csv'));
% csvDat2 = readtable(strrep(nopts.stats_file, '.csv', '.0.csv'));

% Results Section
Results.cpu_time=cpu_time;
Results.xbest = x;
Results.fbest = fval;
Results.neval = nfval;
Results.exitflag = exitflag;
Results.niter = iter;
if length(totfeval)~=nfval
    Results.f = totfeval(2:end);
else
    Results.f = totfeval;
end
Results.toteval = 1:nfval;

evalbest = [];
fevalbest = [];

for i=1:nfval
    if i==1
        fevalbest = Results.f(1);
        evalbest = Results.toteval(1);
    else
        if Results.f(i)<fevalbest(end)
            fevalbest = [fevalbest, Results.f(i)];
            evalbest = [evalbest, Results.toteval(i)];
        end
    end
end
fevalbest = [fevalbest, fevalbest(end)];
evalbest = [evalbest, nfval];
Results.fevalbest = fevalbest;
Results.evalbest = evalbest;



%\-----------------------------------------------------/
% Definition of objective for fminsearchbnd
function fp = fminsobj(x,fun,c_L,c_U,weight,tolc)

[f,c] = feval(fun,x);
pen=ssm_penalty_function(x,c,c_L,c_U,tolc);

fp=f+weight*pen;

%n_fun_eval = n_fun_eval + 1;
return
%\-----------------------------------------------------/

