% $Header: svn://.../trunk/AMIGO2R2016/Kernel/OPT_solvers/ess_options_defaults.m 2086 2015-08-31 07:49:03Z evabalsa $
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                           eSS OPTIONS                                         %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function opts=nomad_options_defaults(varargin)

opts=[];                                                   %options defined by the user
opts.ndiverse=[];
opts.dim_refset=[];
opts.local.balance = 0.5;

if nargin > 0
	xdim = varargin{1};
	opts.maxtime=10*xdim;   % seconds                               
	opts.maxfeval=20000;  
    opts.maxiter=20000;  
	opts.ndiverse=2*xdim;
    opts.inter_save=0;
else
	opts.maxtime=120;
	opts.maxfeval=20000;
    opts.maxiter=20000;
    opts.ndiverse = 'auto';
    opts.log_var = [];
	opts.inter_save=0;
end

opts.maxcachemem = 2000;
opts.history_file = 'ObjectPerIter.csv';
opts.stats_file = 'StatsPerIter.csv';
opts.xtype=[];

opts.iterprint=1;
opts.dim_refset                =       'auto';         %Number of elements in Refset
opts.ndiverse                  =       'auto';         %Number of solutions generated by the diversificator

return